### ISSUE TITLE
Add rough geolocation as use case for IP

### ISSUE THREAD

**Issue by bslassey** [ShivanKaul/draft-ip-address-privacy#10]
IP addresses are used productively in the case of tailoring content to the user's rough geolocation.  There are probably many uses of this rough geolocation information, but two that come immediately to mind are conforming to local laws and providing locally relevant content (for example: a merchant's website showing the nearest physical store, a search engine showing local coffee shops when a user searches for "coffee shop" or a news site showing locally relevant news).

**Comment by sysrqb** [comment]
I'd like to explicitly subdivide this further: 1) legal requirements, and 2) usability.

On the usability aspect, I can see using (something like) a client-hint instead. Client-side software/user-agent will need to determine the correct location (or ask the user), but we shouldn't be bound to using IP addresses as a passive signal for achieving this.

On the other hand, conforming to regional legal restrictions requires nuance, and I won't pretend to be an expert in this area. We should gain an understanding of the limits of these laws and under what circumstances they apply. Specifically, what exact information does a service operator need such that they change how they handle requests to follow the law. And, further, is a client-hint sufficient in most cases, as well?

**Comment by sysrqb** [comment]
Actually, taking a step back from my above comment, we can make sure these use cases are covered in the draft, and then we can dive into answering some of those more specific questions later.
