### ISSUE TITLE
Does a reputation system solve a problem?

### ISSUE THREAD

**Issue by sysrqb** [ShivanKaul/draft-ip-address-privacy#17]
One of the original goals of this draft was describing a "user reputation system" (for example, as a replacement for IP address reputation) that solved problems for platforms, in theory, while giving people/users some measure of control over that reputation. The draft envisioned some amount of transparency and appeal process built in to the system. Recently, this draft is now focusing broadly on a toolbox of replacement signals - each signal replaces some use case of IP addresses. However, where reputation fits into this new collection of signals is not clear, and the breadth/scale of such a reputation system isn't clear either, nor is it clear if such a system is desirable in reality.

**Comment by bslassey** [comment]
I think the text now puts a reputation system as one tool in a toolbox to combat abuse. Do you think this needs further clarificaiton?

**Comment by sysrqb** [comment]
I think that's sufficient.
