### ISSUE TITLE
Counterabuse: law enforcement support.

### ISSUE THREAD

**Issue by jbradleychen** [ShivanKaul/draft-ip-address-privacy#6]
What support should the Internet provide to support legitimate law enforcement inquiries and referrals?

**Comment by sysrqb** [comment]
The framing of this question makes answering it complicated. A motivated attacker/criminal/actor will always find ways to obscure their identity and mislead investigators. A service should not collect more information than it needs "just in case" under the assumption that information could support law enforcement in the future.

Internet protocols and service providers should practice data minimization, as per [RFC 6973](https://datatracker.ietf.org/doc/html/rfc6973#section-6.1).

I'll try posing a slightly different question in the hope of finding a satisfactory answer: What information about users do service providers need to successfully provide their service, and protect themselves, that can also be used by law enforcement?

The answer will vary depending on the service, but enumerating the different types of services and the specific information they need will be helpful.

**Comment by sysrqb** [comment]
These are good points. The reframing I chose specifically equates success in terms of the service provider and user, without providing exceptional access for law enforcement. Public safety is a much larger scope than I originally envisioned.

The framing should capture the importance of public safety, malicious actors, and potentially corrupt and lawless service provides. Can you define/describe public safety within this context and the responsibility (you see) service providers have?

**Comment by jbradleychen** [comment]
Hmm; I think we should try to realize online systems that are at least as private and as safe as the offline alternatives, as much as offline alternatives exist. If we do that, then the public gets better privacy and safety by moving online, avoiding regressions.

If this makes sense to you, then we could think about what tech has done for privacy, and what it has done for safety.

**Comment by jbradleychen** [comment]
As system designers, I think our responsibility is to design systems that, over time, create incentives that favor honesty and truth over dishonesty and deception. Privacy supports honesty and truth by protecting vulnerable individuals. Privacy is not enough though. For individuals whose actions impact public safety, Identity Transparency protects honesty and truth by making it possible for the public to hold  accountable individuals whose actions impact the public.

**Comment by sysrqb** [comment]
This is helpful, thank you. I agree, in general, about replicating (and enhancing) the privacy and safety we have in physical spaces.

There are certainly examples of privacy being necessary for honesty and accountability, as you alluded to (e.g., whistleblowers, political dissidents, human rights defenders, assault/abuse reporters). We know safety nets within society are abused when they are available, and some misuse and deception must be tolerated if the system exists. The threshold of allowed abuse should depend on other factors (e.g., impact/harm resulting from said abuse). I don't know of a specific argument that privacy favors honesty, but I don't know of an argument for privacy favoring deception, either. However, we do know that privacy and security are human rights, and we should therefore build systems that protect people from arbitrary privacy invasion while still limiting deception/misuse/abuse within and of the systems.

I interpret "Identity Transparency" as meaning "revealing the identity of the person who is taking, or responsible for, a specific action". If this is correct, then I agree this transparency can be used for holding people accountable. However, we know that neither retroactive attribution nor up-front identification was sufficient deterrence in multiple well known cases over the last few years, so we should not presume this is a "silver bullet" of dishonesty or malicious activity online.

I think we need a more precise definition and understanding of public safety before we can discuss requirements/expectations associated with it. I am concerned that vague descriptions of public safety will only lead to ineffective mitigations/solutions while creating data-lakes of personal information.

I suspect that separating public safety from law enforcement will be important. however in some cases supporting public safety may require cooperating with law enforcement to some extent.

Would looking at a few specific (offline and online) examples be helpful for describing their responsibility with respect to public safety, and then we can try extrapolating from there? Looking at what technology has done for privacy and safety may be helpful, too, so we have a shared foundation.

I'm not sure working through all of this in comments on an Issue is the best work flow. Should we try drafting another document for these descriptions as a supplement to the original IP address privacy draft? I think this is an important subject, but these details are tangential to the goals of the original draft.

**Comment by bslassey** [comment]
The current draft discusses address escrow, which seems to be aimed at this issue. Can this be closed out?

**Comment by sysrqb** [comment]
Hearing no objections, we'll close this issue.
